### ISSUE TITLE
Sorting and page data inconsistencies

### ISSUE THREAD

**Issue by OWRIG** [trekhleb/trekhleb.github.io#58] opened 2021-10-12 08:10 UTC
![image](https://user-images.githubusercontent.com/50366371/136917113-54fbd9f6-b805-4116-a3d9-d4624cf3ad59.png)
After sorting by stars, click on the item and return to the previous page to reproduce it.

**Comment by trekhleb** [comment] 2021-10-14 08:03
Thanks for reporting! The issue is fixed now.

**Closed by trekhleb** 2021-10-14 08:03 UTC
